#pragma config(Motor,  port1,           lift1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           right,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           left,          tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          left,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#include "ehs.h"

task main() {
	/* SIMULTANEOUS MOVEMENT TEST */
	step(getMoveRight(50, 0), getMoveLeft(50, 0), 127, 600);
	step(getMoveRight(0, 0), getMoveLeft(0, 0), -64, 700);
	step(getMoveRight(-40, 0), getMoveLeft(-40, 0), 64, 500);
	step(getMoveRight(-40, 0), getMoveLeft(-40, 0), 10, 1000);
	step(getMoveRight(-40, 0), getMoveLeft(-40, 0), 5, 1000);*/
}
