#pragma config(Motor,  port1,           lift1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           right,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           left,          tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          left,          tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "ehs.h"

void pre_auton() {
  bStopTasksBetweenModes = true; // LEAVE THIS SET TO TRUE - Cam Morris
}

task autonomous() {
	move(30, 0, 100); // times are guesses, please refine after testing!!!!!!!!!
	lift(127, 100);
	lift(-64, 200);
	move(-30, 0, 1000);
}

task usercontrol() {
	while (true) {
		if (vexRT[Ch4] == 0) {
			motor[right] = quadraticAcceleration(vexRT[Ch2]);
			motor[left] = quadraticAcceleration(vexRT[Ch2]);
		}
		else if (vexRT[Ch4] != 0){
			int ch4val = vexRT[Ch4];
			if (ch4val > 64){
				ch4val = 64 + (ch4val - 64)/2;
				motor[right] = quadraticAcceleration(vexRT[Ch2]) - ch4val;
				motor[left] = quadraticAcceleration(vexRT[Ch2]) + ch4val;
			}
			else {
				motor[right] = quadraticAcceleration(vexRT[Ch2]) - ch4val;
				motor[left] = quadraticAcceleration(vexRT[Ch2]) + ch4val;
			}
		}
		lift(vexRT[Ch1]); // Cam tried overloading here. If it doesn't work rename the function
	}
}
