#pragma config(Motor,  port1,           right,         tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          left,          tmotorVex269_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ehs.h";

/** Allows the robot to drive around in non-tank mode.
 */

task main() {
	while (true) {
		if (vexRT[Ch4] == 0) {
			motor[right] = quadraticAcceleration(vexRT[Ch2]);
			motor[left] = quadraticAcceleration(vexRT[Ch2]);
		}
		else if (vexRT[Ch4] != 0){
			int ch4val = vexRT[Ch4];
			if (ch4val > 64){
				ch4val = 64 + (ch4val - 64)/2;
				motor[right] = quadraticAcceleration(vexRT[Ch2]) - ch4val;
				motor[left] = quadraticAcceleration(vexRT[Ch2]) + ch4val;
			}
			else {
				motor[right] = quadraticAcceleration(vexRT[Ch2]) - ch4val;
				motor[left] = quadraticAcceleration(vexRT[Ch2]) + ch4val;
			}
		}
		lift(vexRT[Ch1]);
	}
}

void lift(short power) {
	motor[lift1] = power;
	motor[lift2] = power;
}
