#pragma config(Motor,  port1,           right,         tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           left,          tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ehs.h";

/** Allows the robot to drive around in tank mode.
 */

task main()
{
	while (true)
	{
			motor[right] = quadraticAcceleration(vexRT[Ch3]);
			motor[left] = quadraticAcceleration(vexRT[Ch2]);
	}
}
