#pragma config(Motor,  port2,           clawOC,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           clawR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           baseBack,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           baseLeft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           baseRight,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           baseFront,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// function prototypes
void lift(short power);

task main() {
	while (true) {
		lift(vexRT[Ch1]);
		if(vexRT[Btn7L] == false|| vexRT[Btn7R] == false)
			move();
		else
			rotate();
	}
}

void lift(short power) {
	motor[lift] = power;
}

void move(){
	motor[baseLeft] = quadraticAcceleration(vexRT[Ch3]);
	motor[baseRight] = quadraticAcceleration(vexRT[Ch3]);
	motor[baseBack] = quadraticAcceleration(vexRT[Ch4]);
	motor[baseFront] = quadraticAcceleration(vexRT[Ch4]);
}

void rotate(){
	//Rotate left
	if(vexRT[Btn7L] == true){
		motor[baseBack] = 64;
		motor[baseFront] = 64;
		motor[baseLeft] = -64;
		motor[baseRight] = -64;
	}
	else if(vexRT[Btn7R] == true){
		motor[baseBack] = -64;
		motor[baseFront] = -64;
		motor[baseLeft] = 64;
		motor[baseRight] = 64;
	}
}
