#pragma config(Motor,  port2,           lift1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,          lift2,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// function prototypes
void lift(short power);

task main() {
	while (true) {
		lift(vexRT[Ch1]);
	}
}

void lift(short power) {
	motor[lift1] = power;
	motor[lift2] = power;
}
