#pragma config(Motor,  port2,           clawOC,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           clawR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           baseBack,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           baseLeft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           baseRight,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           baseFront,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// function prototypes
void lift(short power);
void move();
void rotate();
int quadraticAcceleration(int input);

task main() {
	while (true) {
		lift(vexRT[Ch1]);
		if(vexRT[Btn7L] == 0 || vexRT[Btn7R] == 0)
			move();
		else
			rotate();
		if (vexRT[Btn6U == 1) {
			motor[clawOC] = 50;
		}
		else if (vexRT[Btn6D == 1) {
			motor[clawOC] = -50;
		}
		if (vexRT[Btn5U] == 1) {
			motor[clawR] = 64;
	  }
	  if (vexRT[Btn6U] == 1) {
			motor[clawR] = -64;
	  }
	}
}

void lift(short power) {
	motor[arm] = power;
}

void move(){
	motor[baseLeft] = quadraticAcceleration(vexRT[Ch3]) - vexRT[Ch4] / 2;
	motor[baseRight] = quadraticAcceleration(vexRT[Ch3]) - vexRT[Ch4] / 2;
	motor[baseBack] = vexRT[Ch4] / 2;
	motor[baseFront] = vexRT[Ch4] / 2;
}

void rotate(){
	//Rotate left
	if(vexRT[Btn7L] == true){
		motor[baseBack] = 64;
		motor[baseFront] = 64;
		motor[baseLeft] = -64;
		motor[baseRight] = -64;
	}
	else if(vexRT[Btn7R] == true){
		motor[baseBack] = -64;
		motor[baseFront] = -64;
		motor[baseLeft] = 64;
		motor[baseRight] = 64;
	}
}

int quadraticAcceleration(int input /*! input from the controller (an int between -127 and 127) */) {
	if (input < 0) {
		return (int) ((1.0 / 127.0) * input * input * -1);
	}
	else {
		return (int) ((1.0 / 127.0) * input * input);
	}
}
