#pragma config(Motor,  port1,            ,             tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ehs.h";

/** Allows the robot to drive around. Note that the #pragma config is inaccurate.
 */

task main()
{
	while (true)
	{
			motor[port1] = vexRT[Ch3];
			motor[port2] = vexRT[Ch3];
			motor[port3] = vexRT[Ch1];
			motor[port4] = VexRT[Ch1];
	}
}
// comment for git!